---
# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - go test ./...
  default:
    cmds:
      - go build -o agent ./...
    sources:
      - cmd/agent/*.go
    aliases: [build, agent]
    depends:
      - test
    generates:
      - agent-Linux-amd64
      - agent-Linux-arm64
      - agent-Linux-riscv64
      - agent-Linux-ppc64le
      - agent-Linux-s390x
      - agent-Windows-amd64
      - agent-Windows-arm64
  release:
    cmds:
      # Note: Enable `-buildmode=pie` where possible.
      - GOOS=linux GOARCH=amd64 go build -buildmode=pie -o agent-Linux-amd64 ./...
      - GOOS=linux GOARCH=arm64 go build -buildmode=pie -o agent-Linux-arm64 ./...
      - GOOS=linux GOARCH=ppc64le go build -buildmode=pie -o agent-Linux-ppc64le ./...
      - GOOS=linux GOARCH=riscv64 go build -o agent-Linux-riscv64 ./...
      - GOOS=linux GOARCH=s390x go build -o agent-Linux-s390x ./...

      - GOOS=windows GOARCH=amd64 go build -o agent-Windows-amd64 ./...
      - GOOS=windows GOARCH=arm64 go build -o agent-Windows-arm64 ./...
